# Site settings
title: Sarthak Shukla
description: 'Hi! I am Second Year Undergraduate of Computer Science and Engineering at IIIT Nagpur. I am broadly interested in Data Structures, Algorithms, Competitive programming and their applications. For more details on the academic front, have a look at my resume and profile in links given.'
url: 'http://sarthakeddy.github.io'
# baseurl: '/sarthakeddy.github.io'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sarthak Shukla'
  email: sarthakshukla.eddy@gmail.com
  atcoder_username: sarthak_eddy
  codeforces_username: sarthak_eddy
  codechef_username: sarthak_eddy
  github_username:  sarthakeddy
  linkedin_username:  sarthakeddy

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
